version: '3'

services:
  nginx:
    image: arthurisvi/hello-world-docker:latest
    ports:
      - 8080:80
    volumes:
      - ./www:/usr/share/nginx/html

  goapp:
    build: goapp/
    ports:
      - 8081:80
    volumes:
      - ./goapp:/go/src/app

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbdocker
      MYSQL_USER: admin
      MYSQL_PASSWORD: dev1234

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
